retry curl for up to 30 seconds
crystal-lang/heroku-buildpack-crystal pull request #13
Opened 2016-12-24 07:11 UTC by bacongobbler

2016-12-26 14:42 UTC, bcardiff requested changes
Some flags are duplicated during execution

2016-12-26 14:42 UTC, bcardiff commented on bin/compile
> +  CRYSTAL_VERSION=`${CURL} -s https://api.github.com/repos/crystal-lang/crystal/releases/latest | json_value tag_name 1 | tr -d '\012'`
-s flag is duplicated due to CURL

2016-12-26 14:42 UTC, bcardiff commented on bin/compile
> +${CURL} -sL $CRYSTAL_URL | tar xz -C $CRYSTAL_DIR --strip-component=1
-sL flag is duplicated due to CURL

2016-12-27 18:40 UTC, bacongobbler commented
fixed

2016-12-27 18:57 UTC, merged

2016-12-27 18:58 UTC, bcardiff commented
Thanks