Disable use of the --no-debug if desired
crystal-lang/heroku-buildpack-crystal pull request #26
Opened 2017-10-26 14:30 UTC by danielwestendorf

Compile the application without the --no-debug flag if the DEBUG_ENABLED env variable is set, making debugging optional.

Use case:
I have an application that has an exception being raised on heroku only. The exception could be coming from a number of places, so without debug information, it is very difficult to determine where this bug is coming from.

2017-10-26 14:32 UTC, mverzilli approved these changes

2017-10-26 15:00 UTC, danielwestendorf commented
Compiling without the `--no-debug` flag doesn't work. crystal-lang/crystal#4719

2017-10-26 20:34 UTC, danielwestendorf commented
Per https://stackoverflow.com/questions/46943572/where-to-start-tracing-down-an-exception?noredirect=1#comment80869434_46943572, the `--release` flag is what causes compilation to fail. I've updated the PR to not include the `--release` flag when DEBUG_ENABLED is set.

2017-10-26 20:39 UTC, mverzilli commented
Thanks @danielwestendorf! Would you add a console print with warning explaining that enabling debug will result in a not fully optimized build? Debugging support is pretty experimental right now and inadvertently losing performance because you opted into debug mode will be surprising for most people.

2018-08-13 03:55 UTC, z64 commented
:ping_pong: Any update on this? Was helping some beginner (and work in a community where heroku is very popular with beginners) who had deployed to an app to heroku who ran into some runtime bugs, and being able to deploy with debugging information would certainly help :slightly_smiling_face:

2018-08-13 14:15 UTC, bcardiff requested changes
Rather than `$DEBUG_FLAGS` I would call the `$BUILD_FLAGS` since the value might be:
* `--release --no-debug` (or `--release`) when `DEBUG_ENABLED=0` (default)
* _(empty)_ when `DEBUG_ENABLED=1` 

Otherwise there are too many DEBUG things around and it's kind of confusing IMO.

2018-08-13 14:15 UTC, bcardiff commented on bin/compile
> +    crystal build app.cr --release $DEBUG_FLAGS
there is `--release` left here.

2018-08-13 18:00 UTC, danielwestendorf commented
I'll let someone else take up the torch on this as I no longer need it, and it has been almost a year since the PR was created (I don't remember what I once figured out anymore).

2018-08-13 18:00 UTC, closed without merging

2018-08-13 18:35 UTC, bcardiff commented
100% understandable. Thanks for the notice and the work in the PR.